name: build Dockerfile

on: push
      
jobs:
  push:
    name: "ptero-discord:latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: reashetyrr/ptero-discord
          registry: ghcr.io/reashetyrr/ptero-discord
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          tags: master,latest
