name: build Dockerfile

on:
  push:
    branches:
      - master
    paths:
      - ./**
      
jobs:
  push:
    name: "ptero-discord:latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: reashetyrr/ptero-discord
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          tags: master,latest
