name: build Dockerfile

on: push
      
jobs:
  push:
    name: "ptero-discord"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: ptero-discord
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          tags: master,latest

